version: '3.8'

services:
  django:
    build: .
    container_name: kontat
    volumes:
      - .:/app
    ports:
      - 18000:8000
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DEBUG=1
      - ALLOWED_HOST= 127.0.0.1 localhost

  celery:
    build: .
    container_name: celery
    command: celery -A contact_project worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
