# Generated by Django 3.2.5 on 2021-08-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://res.cloudinary.com/ddl2pf4qh/image/upload/v1627397427/contact_api/user_uaonlt.png'),
        ),
    ]
