# Generated by Django 3.2.5 on 2021-07-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0002_emailmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='avatar',
            field=models.URLField(default='https://res.cloudinary.com/ddl2pf4qh/image/upload/v1627605865/contact_api/avatar3_chs26r.png'),
        ),
    ]
