# Generated by Django 3.2.5 on 2021-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0002_contactmodel_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='intagram',
            new_name='instagram',
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
