# Generated by Django 3.2.5 on 2021-07-24 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0003_auto_20210724_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
